### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by christopherdancy**
Created automated docs with hardhat plugin - which gets regenerated every compile. Used for gitbook docs

### CODE REVIEW

**Comment by christopherdancy** [comment]
> How do these generated docs make their way into the `fractal-docs` repo (Gitbook)? Is that a manual copy/paste process?

Yes. I would love for there to be a automated process but I think there needs to be permissions given

**Review by adamgall — CHANGES_REQUESTED** [review]
@christopherdancy My gut says the generated docs (everything in the `./docs` folder) should not be added to source control, since they're generated artifacts that can always be easily re-generated from the codebase.

**Comment by adamgall** [comment]
@christopherdancy any update on this PR?

**Comment by adamgall** [comment]
Is there still any value in that `@primitivefi/hardhat-dodoc` plugin which _generates_ the `./docs` files?

What did you want to actually _do_ with the documentation that the plugin generates?

**Pull request closed without merging**
